[package]
name = "fieldforge"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.*", features = ["dynamic_linking"] }
tessellation = { version = "0.8.*" }
nalgebra = { version = "0.22.1" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3